# Generated by Django 2.2.8 on 2020-01-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20200118_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='name',
            new_name='neighbourhood',
        ),
    ]
