# Generated by Django 2.2.8 on 2020-01-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20200120_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighbourhood',
            new_name='name',
        ),
    ]
